# Generated by Django 4.2.30 on 2026-04-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
