# Generated by Django 4.2.30 on 2026-04-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_confirmation_number'),
        ('api', '0004_symptomsession_public_id'),
    ]

    operations = [
    ]
