# Generated by Django 4.2 — post-visit (official) diagnosis on symptom sessions

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_merge_20260418_2130"),
    ]

    operations = [
        migrations.AddField(
            model_name="symptomsession",
            name="post_visit_diagnosis",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
